name: my_gallery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/s1.png
    - assets/images/s2.jpg
    - assets/images/s3.jpg
    - assets/images/s4.jpg
    - assets/images/s5.jpg
    - assets/images/s6.png
    - assets/images/s7.jpg
    - assets/images/s8.png
    - assets/images/s9.jpg
    - assets/images/s10.jpg


